language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

before_script:
  # Nothing for us

script: ./gradlew goblobBase:test